#!/bin/bash
# Compari Start Script for Unix/Mac

echo "========================================"
echo "Starting Compari..."
echo "========================================"

# Check if frontend is built
# BUILD_ID is a file generated by Next.js during the build process (not a directory)
if [ ! -f "frontend/.next/BUILD_ID" ]; then
    echo "ERROR: Frontend not built. Run setup.sh first!"
    exit 1
fi

# Start backend and frontend concurrently
echo "Starting backend and frontend..."
npx concurrently -n "API,WEB" -c "blue.bold,green.bold" --kill-others "cd backend && npm start" "cd frontend && npm start"