@echo off
REM Compari Start Script for Windows

echo ========================================
echo Starting Compari...
echo ========================================

REM Check if frontend is built
REM BUILD_ID is a file generated by Next.js during the build process (not a directory)
if not exist "frontend\.next\BUILD_ID" (
    echo ERROR: Frontend not built. Run setup.bat first!
    pause
    exit /b 1
)

REM Start backend and frontend concurrently using concurrently
echo Starting backend and frontend...
call npx concurrently -n "API,WEB" -c "blue.bold,green.bold" --kill-others "cd backend && npm start" "cd frontend && npm start"