/**
 * @module AppError
 * @description Centralized error handler class for the application.
 * Extending standard NodeJS Error prevents TypeScript static analysis alarms
 * and standardizes the explicit status payloads passed to the global error middleware.
 */
class AppError extends Error {
    /**
     * @param {string} message - User-facing error message
     * @param {number} statusCode - HTTP status code
     */
    constructor(message, statusCode) {
        super(message);
        
        this.statusCode = statusCode;
        this.status = statusCode;
        
        // This denotes that the error is explicitly generated by our application logic
        // rather than an unhandled programming/infrastructure failure
        this.isOperational = true;

        // Strip this class call from the stack trace
        Error.captureStackTrace(this, this.constructor);
    }
}

module.exports = AppError;
